name: Main
"on":
  pull_request: {}
  push:
    branches:
      - main
jobs:
  # publish:
  #   needs: validate
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: docker/setup-buildx-action@v3
  #     - uses: docker/login-action@v3
  #       with:
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #     - uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}:latest
  # validate:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.24"
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "24"
  #     - run: make
  deploy:
    # needs: publish
    runs-on: ubuntu-latest
    steps:
      - env:
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
          DOKPLOY_TOKEN: ${{ secrets.DOKPLOY_TOKEN }}
          DOKPLOY_SERVICE: ${{ secrets.DOKPLOY_SERVICE }}
        run: |
          curl -X POST "$DOKPLOY_URL/deploy" \
            -H "Authorization: Bearer $DOKPLOY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "service": "$DOKPLOY_SERVICE"
            }'
