name: Main
"on":
  pull_request: {}
  push:
    branches:
      - main
jobs:
  deploy:
    needs: publish
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: 'curl -X POST "$DOKPLOY_URL/api/application.deploy" -H "x-api-key: $DOKPLOY_TOKEN" -H "Content-Type: application/json" -d ''{"applicationId": "''$DOKPLOY_APP_ID''", "title": "Triggered byGitHub Action"}'''
        env:
          DOKPLOY_APP_ID: ${{ secrets.DOKPLOY_APP_ID }}
          DOKPLOY_TOKEN: ${{ secrets.DOKPLOY_TOKEN }}
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
  publish:
    needs: [validate, build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - run: docker push ghcr.io/${{ github.repository }}:latest
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - run: make
